services:
  api:
    build:
      context: ../vg-sales-api
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - web-net

  frontend:
    build:
      context: ../vg-sales-explorer/frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - web-net

  oauth:
    build:
      context: ../vg-sales-explorer/oauth
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - web-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    networks:
      - web-net
    depends_on:
      - api
      - frontend
      - oauth

networks:
  web-net:
    driver: bridge